name: trigger preview
on:
  workflow_run:
    workflows: ["trigger build"]
    types: [requested, completed]

jobs:
  get-pr-number:
    runs-on: ubuntu-latest
    outputs:
      PR_NUMBER: ${{ steps.get-pr-number.outputs.PR_NUMBER }}
    steps:
    - name: Get PR number
      id: get-pr-number
      run: |
        echo '${{ toJSON(github) }}' > github-context.json
        echo "PR_NUMBER=${{ github.event.workflow_run.pull_requests[0] }}" >> $GITHUB_OUTPUT
        echo ${{ PR_NUMBER }}


  build-for-preview:
    needs: get-pr-number
    uses: './.github/workflows/build.yml'
    with:
      artifact_name: docs-zip-${{ needs.get-pr-number.outputs.PR_NUMBER.number }}
      build_from_code_artifact: true
      code_artifact_name: code-zip-${{ needs.get-pr-number.outputs.PR_NUMBER.number }}
