name: trigger preview
on:
  workflow_run:
    workflows: ["trigger build"]
    types: [requested, completed]

jobs:
  get-pr-number:
    runs-on: ubuntu-latest
    outputs:
      PR_NUMBER: ${{ steps.get-pr-number.outputs.PR_NUMBER }}
    steps:
    - name: Get PR number
      id: get-pr-number
      run: |
        run: echo '${{ toJSON(github.event) }}' > github-context.json
        echo "PR_NUMBER=${{ github.event.workflow_run.event.pull_requests.number }}" >> $GITHUB_OUTPUT

  build-for-preview:
    needs: get-pr-number
    uses: './.github/workflows/build.yml'
    with:
      artifact_name: docs-zip-${{ needs.get-pr-number.outputs.PR_NUMBER }}
      build_from_code_artifact: true
      code_artifact_name: code-zip-${{ needs.get-pr-number.outputs.PR_NUMBER }}
