name: trigger preview
on:
  workflow_run:
    workflows: ["trigger build"]
    types: [requested, completed]

jobs:
  get-pr-number:
    runs-on: ubuntu-latest
    outputs:
      PR_NUMBER: ${{ steps.get-pr-number.outputs.PR_NUMBER }}
    steps:
    - name: Download PR number artifact
      uses: dawidd6/action-download-artifact@v3.1.4
      with:
        name: pr_number
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: trigger-build
        run_id: ${{ github.event.workflow_run.id }}


    - name: Read PR number
      id: get-pr-number
      run: |
        tree .
        cat pr_number.txt
        echo "PR_NUMBER=$(cat pr_number.txt)" >> $GITHUB_OUTPUT

  build-for-preview:
    needs: get-pr-number
    uses: './.github/workflows/build.yml'
    with:
      artifact_name: docs-zip-${{ needs.get-pr-number.outputs.PR_NUMBER.number }}
      build_from_code_artifact: true
      code_artifact_name: code-zip-${{ needs.get-pr-number.outputs.PR_NUMBER.number }}
